export const ACTIONS = {
    /* AUTHENTICATION */
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN: 'LOGIN',
    LOGIN_INVALID:'LOGIN_INVALID',
    LOGIN_ERROR:'LOGIN_ERROR',
    REFRESH_LOGIN_REQUEST:'REFRESH_LOGIN_REQUEST',
    LOGOUT: 'LOGOUT',
    CLEAR_ACCESS_ERROR_MESSAGE: 'CLEAR_ACCESS_ERROR_MESSAGE',
    SET_ACCESS_ERROR_MESSAGE: 'SET_ACCESS_ERROR_MESSAGE',
    GET_USER_DATA: 'GET_USER_DATA',
    GET_USER_DATA_ERROR:'GET_USER_DATA_ERROR',
    GET_USER_DATA_REQUEST: 'GET_USER_DATA_REQUEST',
    INITIATE_PASSWORD_RESET: 'INITIATE_PASSWORD_RESET',
    INITIATE_PASSWORD_RESET_REQUEST: 'INITIATE_PASSWORD_RESET_REQUEST',
    PASSWORD_RESET: 'PASSWORD_RESET',
    PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
    VALIDATE_PASSWORD_RESET: 'VALIDATE_PASSWORD_RESET',
    VALIDATE_PASSWORD_RESET_REQUEST: 'VALIDATE_PASSWORD_RESET_REQUEST',
    INITIATE_SIGN_UP: 'INITIATE_SIGN_UP',
    INITIATE_SIGN_UP_REQUEST: 'INITIATE_SIGN_UP_REQUEST',
    INITIAL_SIGN_UP_ERROR: 'INITIAL_SIGN_UP_ERROR',
    REFRESH_SIGNUP_REQUEST:'REFRESH_SIGNUP_REQUEST',
    SIGN_UP_OTP_VALIDATION: 'SIGN_UP_OTP_VALIDATION',
    SIGN_UP_OTP_VALIDATION_REQUEST: 'SIGN_UP_OTP_VALIDATION_REQUEST',
    SIGN_UP_OTP_VALIDATION_ERROR:'SIGN_UP_OTP_VALIDATION_ERROR',
    SIGN_UP_COMPLETION_REQUEST: 'SIGN_UP_COMPLETION_REQUEST',
    SIGN_UP_COMPLETION: 'SIGN_UP_COMPLETION',
    SIGN_UP_COMPLETION_ERROR:'SIGN_UP_COMPLETION_ERROR',
    REFRESH_SIGN_UP_COMPLETION:'REFRESH_SIGN_UP_COMPLETION',
    UPDATE_BREADCRUMB: 'UPDATE_BREADCRUMB',
    REFRESH_TOKENS:'REFRESH_TOKENS',


    ACTIVITIES_COMPLETION_REQUEST: 'ACTIVITIES_COMPLETION_REQUEST',
    ACTIVITIES_COMPLETION_SUCCESS: 'ACTIVITIES_COMPLETION_SUCCESS',
    REFRESH_ACTIVITIES_COMPLETION: 'REFRESH_ACTIVITIES_COMPLETION',
    ACTIVITIES_COMPLETION_ERROR: 'ACTIVITIES_COMPLETION_ERROR',

    GET_ACTIVITIES_COMPLETION_REQUEST: 'GET_ACTIVITIES_COMPLETION_REQUEST',
    GET_ACTIVITIES_COMPLETION_SUCCESS: 'GET_ACTIVITIES_COMPLETION_SUCCESS',
    GET_REFRESH_ACTIVITIES_COMPLETION: 'GET_REFRESH_ACTIVITIES_COMPLETION',
    GET_ACTIVITIES_COMPLETION_ERROR: 'GET_ACTIVITIES_COMPLETION_ERROR',

        ADD_BASIN_COMPLETION_SUCCESS: 'ADD_BASIN_COMPLETION_SUCCESS',
      ADD_BASIN_COMPLETION_REQUEST: 'ADD_BASIN_COMPLETION_REQUEST',
      ADD_BASIN_COMPLETION_SUCCESS_ERROR: 'ADD_BASIN_COMPLETION_SUCCESS_ERROR',
      REFRESH_ADD_BASIN_COMPLETION_SUCCESS: 'REFRESH_ADD_BASIN_COMPLETION_SUCCESS',

    GET_BASIN_COMPLETION_REQUEST: 'GET_BASIN_COMPLETION_REQUEST',
    GET_BASIN_COMPLETION_SUCCESS: 'GET_BASIN_COMPLETION_SUCCESS',
    GET_REFRESH_BASIN_COMPLETION: 'GET_REFRESH_BASIN_COMPLETION',
    GET_BASIN_COMPLETION_ERROR: 'GET_BASIN_COMPLETION_ERROR',

    ADD_CROP_COMPLETION_REQUEST: 'ADD_CROP_COMPLETION_REQUEST',
    ADD_CROP_COMPLETION_SUCCESS: 'ADD_CROP_COMPLETION_SUCCESS',
    REFRESH_ADD_CROP_COMPLETION: 'REFRESH_ADD_CROP_COMPLETION',
    ADD_CROP_COMPLETION_ERROR:  'ADD_CROP_COMPLETION_ERROR',

    GET_CROP_COMPLETION_REQUEST: 'GET_CROP_COMPLETION_REQUEST',
    GET_CROP_COMPLETION_SUCCESS: 'GET_CROP_COMPLETION_SUCCESS',
    REFRESH_GET_CROP_COMPLETION: 'REFRESH_GET_CROP_COMPLETION',
    GET_CROP_COMPLETION_ERROR:  'GET_CROP_COMPLETION_ERROR',

    ADD_STAGE_COMPLETION_SUCCESS: 'ADD_STAGE_COMPLETION_SUCCESS',
    ADD_STAGE_COMPLETION_REQUEST: 'ADD_STAGE_COMPLETION_REQUEST',
    ADD_STAGE_COMPLETION_SUCCESS_ERROR: 'ADD_STAGE_COMPLETION_SUCCESS_ERROR',

    GET_STAGE_COMPLETION_SUCCESS: 'GET_STAGE_COMPLETION_SUCCESS',
    GET_STAGE_COMPLETION_REQUEST: 'GET_STAGE_COMPLETION_REQUEST',
    GET_STAGE_COMPLETION_ERROR: 'GET_STAGE_COMPLETION_ERROR',

    ADD_NOTIFICATION_COMPLETION_REQUEST: 'ADD_NOTIFICATION_COMPLETION_REQUEST',
    ADD_NOTIFICATION_COMPLETION_SUCCESS: 'ADD_NOTIFICATION_COMPLETION_SUCCESS',
    ADD_NOTIFICATION_COMPLETION_ERROR: 'ADD_NOTIFICATION_COMPLETION_ERROR',

    GET_NOTIFICATION_COMPLETION_REQUEST: 'GET_NOTIFICATION_COMPLETION_REQUEST',
    GET_NOTIFICATION_COMPLETION_SUCCESS: 'GET_NOTIFICATION_COMPLETION_SUCCESS',
    GET_NOTIFICATION_COMPLETION_ERROR: 'GET_NOTIFICATION_COMPLETION_ERROR',

    ADD_SCHEDULE_COMPLETION_REQUEST: 'ADD_SCHEDULE_COMPLETION_REQUEST',
    ADD_SCHEDULE_COMPLETION_SUCCESS: 'ADD_SCHEDULE_COMPLETION_SUCCESS',
    ADD_SCHEDULE_COMPLETION_ERROR: 'ADD_SCHEDULE_COMPLETION_ERROR',
    ADD_SCHEDULE_COMPLETION_REFRESH: 'ADD_SCHEDULE_COMPLETION_REFRESH',


    GET_SCHEDULE_COMPLETION_REQUEST: 'GET_SCHEDULE_COMPLETION_REQUEST',
    GET_SCHEDULE_COMPLETION_SUCCESS: 'GET_SCHEDULE_COMPLETION_SUCCESS',
    GET_SCHEDULE_COMPLETION_ERROR: 'GET_SCHEDULE_COMPLETION_ERROR',
    GET_SCHEDULE_COMPLETION_REFRESH: 'GET_SCHEDULE_COMPLETION_REFRESH',
    
}